"""empty message

Revision ID: 33efbf0d44b4
Revises: 458172f14cd9
Create Date: 2021-10-19 20:17:30.300346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33efbf0d44b4'
down_revision = '458172f14cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'todo', 'user', ['todo_Userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    # ### end Alembic commands ###
