"""empty message

Revision ID: 441b4e84739c
Revises: 1eb86020eb66
Create Date: 2021-10-11 01:58:54.268977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441b4e84739c'
down_revision = '1eb86020eb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('key', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'key')
    # ### end Alembic commands ###
