"""empty message

Revision ID: 458172f14cd9
Revises: 59a9497600af
Create Date: 2021-10-19 19:51:34.991602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458172f14cd9'
down_revision = '59a9497600af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'todo', 'user', ['todo_Userid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    # ### end Alembic commands ###
