"""empty message

Revision ID: dce4f435c963
Revises: 89f496f03438
Create Date: 2021-10-11 02:13:39.096302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce4f435c963'
down_revision = '89f496f03438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    # ### end Alembic commands ###
